#!/usr/bin/env bash
# Builds Waypost.app — a native menu-bar app (like Ollama).
# Runs the local server from .venv as a subprocess and shows its status.
set -euo pipefail

cd "$(dirname "$0")/.."          # project root
PROJECT_DIR="$(pwd)"
APP="build/Waypost.app"
rm -rf "$APP"

# 1. Embed the absolute project path — the app knows where to launch the server from.
mkdir -p macos/generated
cat > macos/generated/BuildConfig.swift <<SWIFT
// Generated by macos/build.sh — do not edit by hand.
let projectDir = "$PROJECT_DIR"
SWIFT

# 2. Compile.
mkdir -p "$APP/Contents/MacOS"
echo "▸ swiftc..."
swiftc \
  -O \
  -target arm64-apple-macos14.0 \
  macos/WaypostBar.swift macos/generated/BuildConfig.swift \
  -o "$APP/Contents/MacOS/Waypost" \
  -parse-as-library \
  -framework Cocoa -framework SwiftUI -framework WebKit \
  -sdk "$(xcrun --sdk macosx --show-sdk-path)"

# 3. Assemble the bundle.
cp macos/Info.plist "$APP/Contents/Info.plist"
mkdir -p "$APP/Contents/Resources"

# App icon: from macos/icon.png (preferred) or macos/icon.svg.
build_iconset() {
  local src="$1" kind="$2"
  ICONSET=macos/Waypost.iconset
  rm -rf "$ICONSET"; mkdir -p "$ICONSET"
  for sz in 16 32 64 128 256 512 1024; do
    if [[ "$kind" == png ]]; then
      sips -z "$sz" "$sz" "$src" --out "/tmp/wp_$sz.png" >/dev/null 2>&1
    else
      rsvg-convert -w "$sz" -h "$sz" "$src" -o "/tmp/wp_$sz.png"
    fi
  done
  cp /tmp/wp_16.png  "$ICONSET/icon_16x16.png";      cp /tmp/wp_32.png  "$ICONSET/icon_16x16@2x.png"
  cp /tmp/wp_32.png  "$ICONSET/icon_32x32.png";      cp /tmp/wp_64.png  "$ICONSET/icon_32x32@2x.png"
  cp /tmp/wp_128.png "$ICONSET/icon_128x128.png";    cp /tmp/wp_256.png "$ICONSET/icon_128x128@2x.png"
  cp /tmp/wp_256.png "$ICONSET/icon_256x256.png";    cp /tmp/wp_512.png "$ICONSET/icon_256x256@2x.png"
  cp /tmp/wp_512.png "$ICONSET/icon_512x512.png";    cp /tmp/wp_1024.png "$ICONSET/icon_512x512@2x.png"
  iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/icon.icns" && rm -rf "$ICONSET"
}

if [[ -f macos/icon.png ]]; then
  build_iconset macos/icon.png png
elif [[ -f macos/icon.svg ]] && command -v rsvg-convert >/dev/null 2>&1; then
  build_iconset macos/icon.svg svg
elif [[ -f macos/icon.icns ]]; then
  cp macos/icon.icns "$APP/Contents/Resources/icon.icns"
fi

# PkgInfo — 8 bytes, required by LaunchServices to recognize the .app.
printf 'APPL????' > "$APP/Contents/PkgInfo"

# 4. Register with LaunchServices so `open` works.
xcrun lsregister -f "$APP" >/dev/null 2>&1 || true

# 5. Sync to /Applications/Waypost.app if it exists or is writable
if [[ -d "/Applications/Waypost.app" ]] || [[ -w "/Applications" ]]; then
  echo "▸ Syncing to /Applications/Waypost.app..."
  rm -rf "/Applications/Waypost.app"
  cp -R "$APP" "/Applications/Waypost.app"
  xcrun lsregister -f "/Applications/Waypost.app" >/dev/null 2>&1 || true
fi

echo "✓ $PROJECT_DIR/$APP"
echo "  Double-click — or:  open $APP"
echo "  Server log:          $PROJECT_DIR/var/server.log"
echo "  To autostart: System Settings → General → Login Items → +"